-- Seed default prompts
INSERT OR IGNORE INTO default_prompts (prompt_text, category) VALUES
('What made you smile today?', 'daily'),
('What are you looking forward to?', 'future'),
('Share a small victory from this week', 'reflection'),
('What song is stuck in your head?', 'fun'),
('Describe your day in three words', 'daily'),
('What was the best thing you ate recently?', 'food'),
('If you could relive one moment from today, which would it be?', 'reflection'),
('What is something new you learned this week?', 'learning'),
('What are you grateful for right now?', 'gratitude'),
('What is your comfort meal?', 'food'),
('What is the last thing that made you laugh?', 'fun'),
('If you could have dinner with anyone tonight, who would it be?', 'imagination'),
('What is a goal you have for this month?', 'goals'),
('Share something that surprised you recently', 'reflection'),
('What is your favorite way to spend a Sunday?', 'lifestyle'),
('What is something kind someone did for you?', 'gratitude'),
('What are you currently reading or watching?', 'entertainment'),
('What is a place you would love to visit?', 'travel'),
('What makes you feel most at home?', 'reflection'),
('Share a childhood memory that still makes you happy', 'memories'),
('What is something you are proud of?', 'achievement'),
('What is your favorite season and why?', 'preferences'),
('What is one thing you would like to learn?', 'learning'),
('Describe your perfect weekend', 'lifestyle'),
('What is a simple pleasure you enjoy?', 'daily'),
('Share a piece of advice you have received', 'wisdom'),
('What is your go-to coffee or tea order?', 'food'),
('What is something you do to relax?', 'self-care'),
('What is a recent act of kindness you witnessed?', 'gratitude'),
('What is your favorite tradition?', 'family'),
('Share something beautiful you saw today', 'daily'),
('What is a challenge you overcame recently?', 'achievement'),
('What makes you feel energized?', 'reflection'),
('What is your favorite way to celebrate good news?', 'celebration'),
('Share a quote or phrase that resonates with you', 'wisdom'),
('What is something that always cheers you up?', 'happiness'),
('What is your favorite room in your home and why?', 'lifestyle'),
('What is a skill you would like to improve?', 'goals'),
('Describe a perfect meal', 'food'),
('What is something you appreciate about where you live?', 'gratitude'),
('What is the best gift you have ever received?', 'memories'),
('Share something you are curious about', 'learning'),
('What is a hobby you would like to try?', 'interests'),
('What makes you feel peaceful?', 'reflection'),
('What is your favorite way to start the day?', 'daily'),
('Share a moment when you felt proud of someone else', 'relationships'),
('What is something you would tell your younger self?', 'wisdom'),
('What is your favorite type of weather?', 'preferences'),
('What is a sound you find soothing?', 'senses'),
('Share something that inspired you this week', 'inspiration'),
('What is your favorite holiday and why?', 'celebration'),
('What is something you do that makes you lose track of time?', 'passion'),
('What is a smell that brings back memories?', 'senses'),
('Share a recent compliment you received', 'gratitude'),
('What is your favorite way to spend time with loved ones?', 'relationships'),
('What is something you have changed your mind about?', 'growth'),
('What is a book or movie that impacted you?', 'entertainment'),
('Share something you are looking forward to this week', 'future'),
('What is your favorite thing about your current phase of life?', 'reflection'),
('What is a fear you have overcome?', 'achievement'),
('What is your favorite dessert?', 'food'),
('Share a lesson you learned the hard way', 'wisdom'),
('What is something you wish you did more often?', 'goals'),
('What is your favorite thing to do on a rainy day?', 'lifestyle'),
('What is a recent random act of kindness you did?', 'kindness'),
('Share something that made you feel loved recently', 'relationships'),
('What is your favorite way to be creative?', 'interests'),
('What is something you find fascinating?', 'learning'),
('What is a tradition you would like to start?', 'family'),
('Share a moment of unexpected joy', 'happiness'),
('What is your favorite thing about this time of year?', 'seasonal'),
('What is something you are working on improving?', 'growth'),
('What is your favorite beverage?', 'food'),
('Share something you wish more people knew about you', 'personal'),
('What is a place that holds special meaning for you?', 'memories'),
('What is your favorite way to exercise or move your body?', 'health'),
('What is something you would like to do more spontaneously?', 'adventure'),
('Share a recent moment of gratitude', 'gratitude'),
('What is your favorite thing to do alone?', 'self-care'),
('What is something that always makes you feel better?', 'comfort'),
('What is a quality you admire in others?', 'values'),
('Share your favorite way to spend an evening', 'lifestyle'),
('What is something you have accomplished that you once thought was impossible?', 'achievement'),
('What is your favorite family recipe or meal?', 'food'),
('What is something you are excited to experience for the first time?', 'future'),
('Share a moment when you felt truly content', 'happiness'),
('What is your favorite thing about your daily routine?', 'daily'),
('What is something you would do if you had no fear?', 'dreams'),
('What is a small change that made a big difference in your life?', 'growth'),
('Share your favorite memory from the past year', 'reflection'),
('What is something you love about yourself?', 'self-love'),
('What is your favorite way to connect with nature?', 'outdoors'),
('What is a dream you are working toward?', 'goals'),
('Share something that made today special', 'daily'),
('What is your favorite way to treat yourself?', 'self-care'),
('What is a moment that took your breath away?', 'wonder'),
('What is something you hope never changes?', 'gratitude'),
('Share your favorite thing about being part of this group', 'relationships');
